# Generated by Django 2.1.4 on 2019-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsandworkshops', '0003_auto_20190102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/eventsandworkshops'),
        ),
    ]
