# Generated by Django 2.1.4 on 2019-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190105_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Admin\\Desktop\\olenakovpak\\static'),
        ),
    ]
