# Generated by Django 2.0.6 on 2019-05-07 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='static/genre')),
            ],
        ),
    ]
